bpmprometro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bpmprometro import settings as setting
from bpmprometro import settings
from core.homepage.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('client/', include('core.client.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

core/client/urls.py
from django.conf.urls.static import static
from django.urls import path

from bpmprometro import settings
from core.client.views import *

app_name = 'client'

urlpatterns = [
    path('add/', ClientCreateView.as_view(), name='client_create'),
    path('list/', ClientListView.as_view(), name='client_list'),
    path('update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/start/urls.py
from django.urls import path

from core.start.views import StartView, NotPermsView

app_name = 'start'

urlpatterns = [
    path('', StartView.as_view(), name='start'),
    path('start/notperms/', NotPermsView.as_view(), name='notperms'),
]

core/user/urls.py
from django.conf.urls.static import static
from django.urls import path

from bpmprometro import settings
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('update-password/<int:pk>/', UserPasswordUpdateView.as_view(), name='user_password_update'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/', MyProfileDetailView.as_view(), name='user_profile'),
    path('profile/edit/<int:pk>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/body.html
{% extends 'home.html' %}
{% load static %}


{% block body %}

    <body class="">
        <div class="wrapper ">

            {% include 'sidebar.html' %}

            <div class="main-panel">

                <!-- Navbar -->
                {% include 'header.html' %}
                <!-- End Navbar -->

                <div class="content">
                    <div class="container-fluid">
{#                        {% if messages %}#}
{#                            {% for message in messages %}#}
{#                                <div class="alert alert-{{ message.tags }} alert-with-icon" data-notify="container">#}
{#                                    <button type="button" aria-hidden="true" class="close" data-dismiss="alert">#}
{#                                        <i class="nc-icon nc-simple-remove"></i>#}
{#                                    </button>#}
{#                                    <span data-notify="icon" class="nc-icon nc-bell-55"></span>#}
{#                                    <span data-notify="message">{{ message }}</span>#}
{#                                </div>#}
{#                            {% endfor %}#}
{#                        {% endif %}#}
                    </div>
                    {% block content %}


                    {% endblock %}
                </div>

                {% include 'footer.html' %}

            </div>
        </div>

        {% block javascript %}


        {% endblock %}
    </body>

{% endblock %}

templates/footer.html
<footer class="footer">
    <div class="container">
        <nav>
            <ul class="footer-menu">
                <li>
                    <a href="https://bpmpro.co" target="_blank">
                        Home
                    </a>
                </li>
            </ul>
            <p class="copyright text-center">
                ©
                <script>
                    document.write(new Date().getFullYear())
                </script>
                <a href="https://bpmpro.co" target="_blank">BPMPRO Metrology v1.0</a>, made with love by CielTechno SAS
            </p>
        </nav>
    </div>
</footer>

templates/form.html
{% extends 'body.html' %}
{% load static %}


{% block head %}
    <script src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/js/core/jquery.3.2.1.min.js' %}"></script>
    <script src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/js/plugins/moment.min.js' %}"></script>
    <script src="{% static 'lib/moment-es/es.js' %}"></script>
    <script src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/js/plugins/bootstrap-datetimepicker.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form enctype="multipart/form-data" method="post" action="" class="form-horizontal">
                <div class="card ">
                    <div class="card-header ">
                        <h4 class="card-title">{{ entity }}</h4>
                    </div>
                    <div class="card-body ">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="{{ action }}">
                        {% for field in form.visible_fields %}
                            {% if forloop.first %}
                                <div class="row">
                            {% endif %}
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for=id_{{ field.name }}>
                                    {{ field.label }}
                                </label>
                                {% if field.help_text %}
                                    <sub>*{{ field.help_text }}</sub>
                                {% endif %}
                                {{ field }}
                            </div>
                        </div>
                        {% if forloop.last %}
                        {% elif forloop.counter|divisibleby:3 %}
                            </div>
                            <div class="row">
                        {% endif %}
                        {% endfor %}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-fill btn-success" onclick="showNotification('top','right')"><i class="nc-icon nc-check-2"></i>
                                Guardar
                            </button>
                            <a href="{{ list_url }}" class="btn btn-fill btn-danger"><i
                                    class="nc-icon nc-simple-remove"></i>
                                Cancelar
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });

        $('#date_birth').datetimepicker({
            format: 'YYYY-MM-DD',
            locale: 'es',
            defaultDate: $('.date_birth'),
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove',
            },
        });

    </script>
{% endblock %}

templates/form_two.html
{% extends 'body.html' %}
{% load static %}


{% block head %}
    <script src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/js/core/jquery.3.2.1.min.js' %}"></script>
    <script src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/js/plugins/moment.min.js' %}"></script>
    <script src="{% static 'lib/moment-es/es.js' %}"></script>
    <script src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/js/plugins/bootstrap-datetimepicker.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form enctype="multipart/form-data" method="post" action="" class="form-horizontal">
                <div class="card ">
                    <div class="card-header ">
                        <h4 class="card-title">{{ entity }}</h4>
                    </div>
                    <div class="card-body ">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="{{ action }}">
                        {% for field in form.visible_fields %}
                            {% if forloop.first %}
                                <div class="row">
                            {% endif %}
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for=id_{{ field.name }}>
                                    {{ field.label }}
                                </label>
                                {% if field.help_text %}
                                    <sub>*{{ field.help_text }}</sub>
                                {% endif %}
                                {{ field }}
                            </div>
                        </div>
                        {% if forloop.last %}
                        {% elif forloop.counter|divisibleby:4 %}
                            </div>
                            <div class="row">
                        {% endif %}
                        {% endfor %}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-fill btn-success"><i class="nc-icon nc-check-2"></i>
                                Guardar
                            </button>
                            <a href="{{ list_url }}" class="btn btn-fill btn-danger"><i
                                    class="nc-icon nc-simple-remove"></i>
                                Cancelar
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });

        $('#date_birth').datetimepicker({
            format: 'YYYY-MM-DD',
            locale: 'es',
            defaultDate: $('.date_birth'),
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove',
            },
        });

    </script>
{% endblock %}

templates/header.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-primary btn-fill btn-round btn-icon d-none d-lg-block">
                    <i class="fa fa-ellipsis-v visible-on-sidebar-regular"></i>
                    <i class="fa fa-navicon visible-on-sidebar-mini"></i>
                </button>
            </div>
            <a class="navbar-brand" href="#"> Nombre logo Empresa </a>
        </div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="nav navbar-nav mr-auto">
{#                <form class="navbar-form navbar-left navbar-search-form" role="search">#}
{#                    <div class="input-group">#}
{#                        <i class="nc-icon nc-zoom-split"></i>#}
{#                        <input type="text" value="" class="form-control" placeholder="Search...">#}
{#                    </div>#}
{#                </form>#}
            </ul>
            <ul class="navbar-nav">
                <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <i class="nc-icon nc-planet"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <a class="dropdown-item" href="#">Create New Post</a>
                        <a class="dropdown-item" href="#">Manage Something</a>
                        <a class="dropdown-item" href="#">Do Nothing</a>
                        <a class="dropdown-item" href="#">Submit to live</a>
                        <li class="divider"></li>
                        <a class="dropdown-item" href="#">Another action</a>
                    </ul>
                </li>
                <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <i class="nc-icon nc-bell-55"></i>
                        <span class="notification">5</span>
                        <span class="d-lg-none">Notification</span>
                    </a>
                    <ul class="dropdown-menu">
                        <a class="dropdown-item" href="#">Notification 1</a>
                        <a class="dropdown-item" href="#">Notification 2</a>
                        <a class="dropdown-item" href="#">Notification 3</a>
                        <a class="dropdown-item" href="#">Notification 4</a>
                        <a class="dropdown-item" href="#">Notification 5</a>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="nc-icon nc-bullet-list-67"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">
                            <i class="nc-icon nc-email-85"></i> Messages
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="nc-icon nc-umbrella-13"></i> Help Center
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="nc-icon nc-settings-90"></i> Settings
                        </a>
                        <div class="divider"></div>
                        <a class="dropdown-item" href="#">
                            <i class="nc-icon nc-lock-circle-open"></i> Lock Screen
                        </a>
                        <a href="{% url 'logout' %}" class="dropdown-item text-danger">
                            <i class="nc-icon nc-button-power"></i> Log out
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

templates/sidebar.html
{% load static %}
<!--Sidebar-->
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
<div class="sidebar" data-color="blue" data-image="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/img/sidebar-5.jpg' %}">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="#" class="simple-text logo-mini">
                BM
            </a>
            <a href="{% url 'start:start' %}" class="simple-text logo-normal">
                BPMPRO METRO
            </a>
        </div>
        <div class="user">
            <div class="photo">
                {% if request.user.photo %}
                    <img src="{{ request.user.photo.url }}" alt="photo_user"/>
                {% else %}
                    <img src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/img/default-avatar.png' %}"
                     alt="photo_user"/>
                {% endif %}
            </div>
            <div class="info ">
                <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                    <span>{{ request.user.get_full_name }}<b class="caret"></b></span>
                </a>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <li>
                            <a class="profile-dropdown" href="{% url 'user:user_profile' request.user.id %}">
                                <span class="sidebar-mini">MP</span>
                                <span class="sidebar-normal">Mi Perfil</span>
                            </a>
                        </li>
                        <li>
                            <a class="profile-dropdown" href="{% url 'user:change_password' %}">
                                <span class="sidebar-mini">CP</span>
                                <span class="sidebar-normal">Cambiar Contraseña</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'start:start' %}">
                    <i class="nc-icon nc-grid-45"></i>
                    <p>Inicio</p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#clients">
                    <i class="nc-icon nc-badge"></i>
                    <p>
                        Clientes
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse " id="clients">
                    <ul class="nav">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'client:client_list' %}">
                                <span class="sidebar-mini">LC</span>
                                <span class="sidebar-normal">Listado Clientes</span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'client:client_create' %}">
                                <span class="sidebar-mini">NC</span>
                                <span class="sidebar-normal">Nuevo Cliente</span>
                            </a>
                        </li>
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./components/panels.html">#}
{#                                <span class="sidebar-mini">P</span>#}
{#                                <span class="sidebar-normal">Panels</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./components/sweet-alert.html">#}
{#                                <span class="sidebar-mini">SA</span>#}
{#                                <span class="sidebar-normal">Sweet Alert</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./components/notifications.html">#}
{#                                <span class="sidebar-mini">N</span>#}
{#                                <span class="sidebar-normal">Notifications</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./components/icons.html">#}
{#                                <span class="sidebar-mini">I</span>#}
{#                                <span class="sidebar-normal">Icons</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./components/typography.html">#}
{#                                <span class="sidebar-mini">T</span>#}
{#                                <span class="sidebar-normal">Typography</span>#}
{#                            </a>#}
{#                        </li>#}
                    </ul>
                </div>
            </li>
{#            <li class="nav-item">#}
{#                <a class="nav-link" data-toggle="collapse" href="#formsExamples">#}
{#                    <i class="nc-icon nc-notes"></i>#}
{#                    <p>#}
{#                        Forms#}
{#                        <b class="caret"></b>#}
{#                    </p>#}
{#                </a>#}
{#                <div class="collapse " id="formsExamples">#}
{#                    <ul class="nav">#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./forms/regular.html">#}
{#                                <span class="sidebar-mini">Rf</span>#}
{#                                <span class="sidebar-normal">Regular Forms</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./forms/extended.html">#}
{#                                <span class="sidebar-mini">Ef</span>#}
{#                                <span class="sidebar-normal">Extended Forms</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./forms/validation.html">#}
{#                                <span class="sidebar-mini">Vf</span>#}
{#                                <span class="sidebar-normal">Validation Forms</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./forms/wizard.html">#}
{#                                <span class="sidebar-mini">W</span>#}
{#                                <span class="sidebar-normal">Wizard</span>#}
{#                            </a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" data-toggle="collapse" href="#tablesExamples">#}
{#                    <i class="nc-icon nc-paper-2"></i>#}
{#                    <p>#}
{#                        Tables#}
{#                        <b class="caret"></b>#}
{#                    </p>#}
{#                </a>#}
{#                <div class="collapse " id="tablesExamples">#}
{#                    <ul class="nav">#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./tables/regular.html">#}
{#                                <span class="sidebar-mini">RT</span>#}
{#                                <span class="sidebar-normal">Regular Tables</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./tables/extended.html">#}
{#                                <span class="sidebar-mini">ET</span>#}
{#                                <span class="sidebar-normal">Extended Tables</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./tables/bootstrap-table.html">#}
{#                                <span class="sidebar-mini">BT</span>#}
{#                                <span class="sidebar-normal">Bootstrap Table</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./tables/datatables.net.html">#}
{#                                <span class="sidebar-mini">DT</span>#}
{#                                <span class="sidebar-normal">DataTables.net</span>#}
{#                            </a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" data-toggle="collapse" href="#mapsExamples">#}
{#                    <i class="nc-icon nc-pin-3"></i>#}
{#                    <p>#}
{#                        Maps#}
{#                        <b class="caret"></b>#}
{#                    </p>#}
{#                </a>#}
{#                <div class="collapse " id="mapsExamples">#}
{#                    <ul class="nav">#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./maps/google.html">#}
{#                                <span class="sidebar-mini">GM</span>#}
{#                                <span class="sidebar-normal">Google Maps</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./maps/vector.html">#}
{#                                <span class="sidebar-mini">VM</span>#}
{#                                <span class="sidebar-normal">Vector maps</span>#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item ">#}
{#                            <a class="nav-link" href="./maps/fullscreen.html">#}
{#                                <span class="sidebar-mini">FSM</span>#}
{#                                <span class="sidebar-normal">Full Screen Map</span>#}
{#                            </a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </li>#}
{#            <li class="nav-item ">#}
{#                <a class="nav-link" href="./charts.html">#}
{#                    <i class="nc-icon nc-chart-bar-32"></i>#}
{#                    <p>Charts</p>#}
{#                </a>#}
{#            </li>#}
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#pagesExamples">
                    <i class="nc-icon nc-single-02"></i>
                    <p>
                        Usuarios
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse " id="pagesExamples">
                    <ul class="nav">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'user:user_list' %}">
                                <span class="sidebar-mini">LU</span>
                                <span class="sidebar-normal">Lista Usuarios</span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'user:user_create' %}">
                                <span class="sidebar-mini">CU</span>
                                <span class="sidebar-normal">Crear Usuario</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>