bpmprometro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bpmprometro import settings as setting
from bpmprometro import settings
from core.homepage.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('client/', include('core.client.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

core/user/urls.py
from django.conf.urls.static import static
from django.urls import path

from bpmprometro import settings
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('update-password/<int:pk>/', UserPasswordUpdateView.as_view(), name='user_password_update'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/', MyProfileDetailView.as_view(), name='user_profile'),
    path('profile/edit/<int:pk>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from bpmprometro.settings import MEDIA_URL, STATIC_URL


# Usuarios
class User(AbstractUser):
    cedula = models.CharField(max_length=15, null=True, blank=True, unique=False, verbose_name='Cédula')
    cargo = models.CharField(max_length=50, null=True, blank=True, verbose_name='Cargo')
    email_person = models.EmailField(null=True, blank=True, verbose_name='Email Personal')
    cellphone = models.CharField(max_length=10, null=True, blank=True, verbose_name='N° Celular')
    address_user = models.CharField(max_length=50, null=True, blank=True, verbose_name='Dirección')
    date_birth = models.DateField(null=True, blank=True, verbose_name='Fecha de Nacimiento')
    photo = models.ImageField(upload_to='user/%Y%m%d', null=True, blank=True, verbose_name='Foto')

    def __str__(self):
        return f'{self.get_full_name()}, {self.cargo}'

    def get_image(self):
        if self.photo:
            return '{}{}'.format(MEDIA_URL, self.photo)
        return '{}{}'.format(STATIC_URL, 'img/default-avatar.jpg')

core/user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, UpdateView, DetailView, FormView

from core.mixins import ValidatePermissionRequiredMixin
from core.user.forms import *
from core.user.models import User


# Creacion de usuario
class UserCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'create_user.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.add_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    name_username = form.cleaned_data.get('username')
                    messages.success(request, f'Usuario "{name_username}" creado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de Usuarios'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        context['entity'] = 'Creación de Usuario'
        return context


# Listado de usuarios
class UserListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = User
    template_name = 'list_user.html'
    permission_required = 'user.add_user'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                usuarios = list(User.objects.values(
                    'id',
                    'date_joined',
                    'last_login',
                    'cedula',
                    'username',
                    'cargo',
                    'groups__name',
                    'email',
                    'is_active',
                    'first_name',
                    'last_name'
                ).filter(is_superuser=False).order_by('first_name'))
                return JsonResponse(usuarios, safe=False)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Usuarios'
        context['create_url'] = reverse_lazy('user:user_create')
        context['list_url'] = reverse_lazy('user:user_list')
        context['entity'] = 'Usuarios'
        return context


# Edicion de usuario por Administrador
class UserUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'create_user.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    name_username = form.cleaned_data.get('username')
                    messages.success(request, f'Usuario "{name_username}" actualizado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de Usuarios'
        context['list_url'] = self.success_url
        context['entity'] = 'Editar Usuario'
        context['action'] = 'edit'
        context['users'] = User.objects.all()
        return context


# Detalle de Usuario por administrador
class UserDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = User
    template_name = 'detail_user.html'
    permission_required = 'user.change_user'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(UserDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Perfil de Usuario'
        context['entity'] = 'Perfil de Usuario'
        context['list_url'] = reverse_lazy('user:user_list')
        return context


# Detalle de Perfil de usuario logueado
class MyProfileDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = User
    template_name = 'detail_user.html'
    permission_required = 'user.view_user'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(MyProfileDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mi Perfil'
        context['entity'] = 'Mi Perfil'
        context['list_url'] = reverse_lazy('inicio:inicio')
        return context


# Edicion de perfil por usuario logueado
class ProfileUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = ProfileUpdateForm
    template_name = 'create_user.html'
    success_url = reverse_lazy('inicio:inicio')
    permission_required = 'user.view_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    messages.success(request, f'Su perfil ha sido actualizado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Perfil'
        context['list_url'] = reverse_lazy('user:user_profile', kwargs={'pk': self.kwargs.get('pk')})
        context['entity'] = 'Editar Perfil'
        context['action'] = 'edit'
        return context


# Reseteo de contraseña por administrador
class UserPasswordUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserPasswordUpdateForm
    template_name = 'update_password.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    messages.success(request, f'Contraseña de usuario reseteada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reseteo de Contraseña'
        context['list_url'] = self.success_url
        context['entity'] = 'Reseteo de Contraseña de Usuario'
        context['action'] = 'edit'
        return context


# Cambio de contraseña por usuario
class UserChangePasswordView(LoginRequiredMixin, ValidatePermissionRequiredMixin, FormView):
    model = User
    form_class = PasswordChangeForm
    template_name = 'update_password.html'
    permission_required = 'user.view_user'
    success_url = reverse_lazy('start:start')

    @method_decorator(csrf_exempt)

core/user/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

core/user/templates/create_user.html
{% extends 'form.html' %}

core/user/templates/detail_user.html
{% extends 'body.html' %}
{% load static %}
{% load widget_tweaks %}


{% block head %}

{% endblock %}

{% block content %}

    <div class="section-image" data-image="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/img/bg5.jpg' %}">
        <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6">
                    <div class="card ">
                            <div class="card-header ">
                                <div class="card-header">
                                    <h4 class="card-title">{{ entity }}</h4>
                                </div>
                            </div>
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-4 pr-1">
                                        <label>N° Identificación</label><p>{{ object.cedula }}</p>
                                    </div>
                                    <div class="col-md-4 px-1">
                                        <label>Usuario</label><p>{{ object.username }}</p>
                                    </div>
                                    <div class="col-md-4 pl-1">
                                        <label>E-mail</label><p>{{ object.email }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 pr-1">
                                        <label>Nombres</label><p>{{ object.first_name }}</p>
                                    </div>
                                    <div class="col-md-4 pl-1">
                                        <label>Apellidos</label><p>{{ object.last_name }}</p>
                                    </div>
                                    <div class="col-md-4 pl-1">
                                        <label>Cargo</label><p>{{ object.cargo }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Dirección</label>
                                        <p>
                                            {% if object.address_user == None %}
                                                No Registrado
                                            {% else %}
                                                {{ object.address_user }}
                                            {% endif %}
                                        </p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 pr-1">
                                        <label>Fecha de Nacimiento</label>
                                        <p>
                                            {% if object.date_birth == None %}
                                                No Registrado
                                            {% else %}
                                                {{ object.date_birth }}
                                            {% endif %}
                                        </p>
                                    </div>
                                    <div class="col-md-4 px-1">
                                        <label>E-mail Personal</label>
                                        <p>
                                            {% if object.email_person == None %}
                                                No Registrado
                                            {% else %}
                                                {{ object.email_person }}
                                            {% endif %}
                                        </p>
                                    </div>
                                    <div class="col-md-4 pl-1">
                                       <label>Celular</label><p>{{ object.cellphone }}</p>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                </div>
                <div class="col-md-4">
                    <div class="card card-user">
                        <div class="card-header no-padding">
                            <div class="card-image">
                                {% if user.photo %}
                                    <img src="{{ user.photo.url }}" alt="user_profile">
                                {% else %}
                                    <img src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/img/full-screen-image-3.jpg' %}" alt="user_profile">
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-body ">
                            <div class="author">
                                <a href="#">
                                    <img class="avatar border-gray" src="{% static 'lib/light-bootstrap-dashboard-pro-html-v2.0.1/img/default-avatar.png' %}" alt="user_photo">
                                    <h5 class="card-title">{{ object.get_full_name }}</h5>
                                </a>
                                <p class="card-description">
                                    {{ object.cargo }}
                                </p>
                                {% if object.is_active == True %}
                                    <p class="card-description" style="color: green; font-weight: bold">Activo</p>
                                {% else %}
                                    <p class="card-description" style="color: red; font-weight: bold">Inactivo</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                            <div class="button-container text-center">
                                {% if entity == 'Mi Perfil' %}
                                    <a href="{% url 'user:user_profile_update' object.id %}"
                                       class="btn btn-info btn-fill pull-center">Editar Perfil</a>
                                {% else %}
                                    <a href="{% url 'user:user_update' object.id %}"
                                       class="btn btn-info btn-fill pull-center">Editar Perfil</a>
                                {% endif %}
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/user/templates/list_user.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'list_user.js' %}"></script>
{% endblock %}

{#{% block new_create %}#}
{#    <a href="{% url 'user:user_create' %}" class="btn btn-primary">Crear Nuevo</a>#}
{#{% endblock %}#}

{% block columns %}
    <tr>
        <th class="text-md-center" style="width:3%"></th>
        <th class="text-md-center" style="width:22%">Nombre Completo</th>
        <th class="text-md-center" style="width:12%">Usuario</th>
        <th class="text-md-center" style="width:16%">Cargo</th>
        <th class="text-md-center" style="width:10%">Rol</th>
        <th class="text-md-center" style="width:20%">Email</th>
        <th class="text-md-center" style="width:12%">Estado</th>
        <th class="disabled-sorting text-right" style="width:5%">Editar</th>
    </tr>
{% endblock %}
{% block columns_foot %}
    <tr>
        <th class="text-md-center" style="width:3%"></th>
        <th class="text-md-center" style="width:22%">Nombre Completo</th>
        <th class="text-md-center" style="width:12%">Usuario</th>
        <th class="text-md-center" style="width:16%">Cargo</th>
        <th class="text-md-center" style="width:10%">Rol</th>
        <th class="text-md-center" style="width:20%">Email</th>
        <th class="text-md-center" style="width:12%">Estado</th>
        <th class="disabled-sorting text-right" style="width:5%">Editar</th>
    </tr>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}


{% endblock %}

core/user/templates/update_password.html
{% extends 'body.html' %}
{% load static %}


{% block head %}

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <form enctype="multipart/form-data" method="post" action="" class="form-horizontal">
                <div class="card ">
                    <div class="card-header ">
                        <h4 class="card-title">{{ entity }}</h4>
                    </div>
                    <div class="card-body ">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="{{ action }}">
                        {% for field in form.visible_fields %}
                            <div class="col-md-10">
                                <div class="form-group">
                                    <label for=id_{{ field.name }}>
                                        {{ field.label }}
                                    </label>
                                    <star class="star">*</star>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <sub>*{{ field.help_text }}</sub>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-fill btn-success"><i class="nc-icon nc-check-2"></i>
                            Guardar
                        </button>
                        <a href="{{ list_url }}" class="btn btn-fill btn-danger"><i
                                class="nc-icon nc-simple-remove"></i>
                            Cancelar
                        </a>
                    </div>

                </div>
        </div>
        </form>
    </div>
    </div>

    <script type="text/javascript">

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });

    </script>
{% endblock %}